### PR TITLE
refactor: TypeScript rewrite

### PR DESCRIPTION
**Pull request by guidojw**
The greater version of https://github.com/guidojw/arora-api/pull/263

This PR introduces two new dependencies:
- `TypeORM`: replaces Sequelize. The migration is made in such a way that it only migrates if the Sequelize migration table doesn't exist. If it exists, the migration removes it and skips all other migrations. I ran a comparison on my local pgAdmin between the schemas created with Sequelize and TypeORM and, apart from some key names, there are no other differences. Because we're using a new ORM dependency now, all the old Sequelize tests have been removed, this is reflected in #109.

- `Inversify`: This is a Dependency Injection dependency used to make the overall sharing of dependencies between classes easier and also to make implementing tests in the future more convenient. `inversify-inject-decorators` was also added to fix DI on classes not instanced by Inversify itself.

TypeScript module augmentation is used on all the Discord.js extensions and the Client class to reflect the types of all the custom added fields on those. With the soonTM Discord.js v13 update, these declarations will be removed.

The fields of type Emoji in the TicketType and RoleMessage entities are commented because of the same named field containing the emoji name. This will be fixed in a later PR when those entities move to using the new Discord buttons.

### CODE REVIEW

**Comment by guidojw** [comment]
Removed the boilerplate code for custom repositories + class-transformer because scopes are not needed in this project. Can just use relations: string[] here to include relations on querying data from the database.

**Comment by guidojw** [comment]
Jobs are still scheduled on a per guild basis, might revisit later.

**Comment by guidojw** [comment]
Switched ChannelEntity.toLinks and .fromLinks so probably have to remove them using the commands before merging this.

**Review by naimeds10 — APPROVED** [review]
Nice code bro

**Pull request merged**
